// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQaFc7nLHS2MIABFPaFG-g0GCeXpXL5GU',
    appId: '1:1032065240160:web:34309e441d1eae19c68705',
    messagingSenderId: '1032065240160',
    projectId: 'movie-7660e',
    authDomain: 'movie-7660e.firebaseapp.com',
    storageBucket: 'movie-7660e.appspot.com',
    measurementId: 'G-7L1XD9CZW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnF5W8exCw94Ik_TL2Fv0sQULdJm5hYw8',
    appId: '1:1032065240160:android:cbf190f23b027a89c68705',
    messagingSenderId: '1032065240160',
    projectId: 'movie-7660e',
    storageBucket: 'movie-7660e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpfmy3e9l53s7YlbL8RUVXMPqHwd_brGQ',
    appId: '1:1032065240160:ios:7fe2408dacb11b87c68705',
    messagingSenderId: '1032065240160',
    projectId: 'movie-7660e',
    storageBucket: 'movie-7660e.appspot.com',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpfmy3e9l53s7YlbL8RUVXMPqHwd_brGQ',
    appId: '1:1032065240160:ios:84bb34cb5c1e9065c68705',
    messagingSenderId: '1032065240160',
    projectId: 'movie-7660e',
    storageBucket: 'movie-7660e.appspot.com',
    iosBundleId: 'com.example.movie.RunnerTests',
  );
}
